### ISSUE TITLE
EPL multiple combination of copyright owners

### ISSUE THREAD

**Issue by skabashnyuk** [mathieucarbou/license-maven-plugin#119]
Hello
I'm a Eclipse Che developer and I have one question related to license check
EPL looks like this.

```
/*******************************************************************************
 * Copyright (c) {DATE} {INITIAL COPYRIGHT OWNER} {OTHER COPYRIGHT OWNERS}.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    {INITIAL AUTHOR} - initial API and implementation and/or initial documentation
 *    {Second AUTHOR} - Dev API
 *******************************************************************************/
```

Until some time we have one or two copyright owners. 
I've managed this with different templates and with configuration of individual maven
modules. In the case if one module contains several owners we just exclude files
with different owners. Now situation become complex. 
So I need to have ability to correctly manage several combination of owners in single module
Ideally without plugin configuration change.
Any ideas how to achieve that.

**Comment by TylerJewell** [comment]
** bump **

**Comment by cvgaviao** [comment]
Well, I have not tried yet, but I think you can achieve this declaring the properties configuration and set all the owners in a pom properties:

    <properties>
        <owner>${license.copyrightOwners}</owner>
    </properties>

**Comment by skabashnyuk** [comment]
It works if one module contains sources with a single list of  ```license.copyrightOwners```. My problem and the goal of this issue to solve situation if single module contains different sources with different combination of ```copyrightOwners```

**Comment by flefevre** [comment]
Do you have found any solution?

**Comment by mathieucarbou** [comment]
@skabashnyuk : how could the plugin determine per file which authors to put in a header ?
The request is nice but I don't see how it could be easily implemented without providing some mapping somewhere...
If such use cases are limited in your code-base, you can exclude the files from license maven plugin and manage the headers yourself perhaps ?

**Comment by skabashnyuk** [comment]
>how could the plugin determine per file which authors to put in a header ?

In our case https://github.com/eclipse/che. One of the trickiest situations was if
there is a jar that contains a lot of files and majority of the classes have one set of authors
however ~10-20 has two or three others. Having individual configuration will look complex.
Putting all that files to ignore(what we are doing right now) has some disadvantiages - like skiping
license check in future,  not automatically update of years.

I would say this task should be separate on two distinct topics.
1. How to generate a new header.
   For this case, we may reuse the current approach. 
2. How to check existed header.
   I would say we should be able to explain in the template that some additional characters may happen here and license
   the plugin should not fail if it saw something.

the first thing that comes to mind something like this:

```
Copyright (c) ${license.git.copyrightYears} ${h_copyrightOwner}*
This program and the accompanying materials are made
available under the terms of the Eclipse Public License 2.0
which is available at https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0

Contributors:
  ${h_contributor}*
```
