### ISSUE TITLE
Support different output formats

### ISSUE THREAD

**Issue by php-coder** [mathieucarbou/license-maven-plugin#122]
I'm using license-maven-plugin to only check the sources when a new PR is submitted. I didn't find a way to get the messages in the machine-readable form (XML/JSON). It would be great to have such feature because it could be used in automatization and integration with external plugins/bots.

**Comment by mathieucarbou** [comment]
Hi @php-coder,
The plugin uses the maven infrastructure to output and log so there are some formatting out of our control. 
Though, we could eventually "bufferize" the logs and at the end of the execution, output the result in some format (json or xml) in a target directory.
This would be a kind of report, that could be used for some reporting tools.

**Comment by mathieucarbou** [comment]
Implemented in PR https://github.com/mathieucarbou/license-maven-plugin/pull/227.

See report examples when running `ReportTest`

See updated plugin doc: https://mycila.carbou.me/license-maven-plugin/reports/4.2-SNAPSHOT/license-maven-plugin/plugin-info.html
