### ISSUE TITLE
Add ability to skip run when using git configuration and git not present

### ISSUE THREAD

**Issue by hazendaz** [mathieucarbou/license-maven-plugin#123]
In cases where a brand new project not yet committed to git or where dev/ops might run build outside of git control, it would be nice to have a setting to skip throwing errors when git variables cannot be calculated.  In this case, check early for presence of git and if not present, skip run writing output once that run was skipped.  Is this possible or will some assistance be needed to possibly bring this in?

**Comment by mathieucarbou** [comment]
Can't you use the `license.skip` flag and set it to the maven command-line or elsewhere when you detect that there is no `.git` folder ?
