### ISSUE TITLE
Allow wildcard year check

### ISSUE THREAD

**Issue by sgreenslade** [mathieucarbou/license-maven-plugin#124]
Would it be possible to check that a year number exists, but not a specific year?

Use Case:
As we write code we include the year the file was first created in the header, this differs from the projects inception year.

**Comment by RiRomain** [comment]
Same problem for me, that would be a nice feature. And I suppose it's not so complicated to implement, instead of checking against a String it could accept regex pattern.

**Comment by mathieucarbou** [comment]
Not using the git extension, this is a request that is quite hard to implement...

**Comment by xenomachina** [comment]
Checking specific years seems way too brittle. Really, I'd just like a way to have it check that the *some* sequence of year ranges was provided. A regex something like:

    (\d\d\d\d)(-\d\d\d\d)?(,(\d\d\d\d)(-\d\d\d\d)?)*

Forgetting to include a copyright header is easy to miss in code review, but adding a copyright header with a bogus year, and having that survive code review, seems very unlikely.

The way things are now, the plugin is constantly trying to add copyright headers with the wrong year even when there's already an existing header with a year that it just doesn't recognize.

**Comment by mathieucarbou** [comment]
I still don't have any idea how to correctly (not a hacky way) implement that and also solve @afranken's issue in [S3Mock](https://github.com/adobe/S3Mock/issues/241).
Looking at the git creation time seems the best choice atm...
