### ISSUE TITLE
Auto detect type of extension-less files

### ISSUE THREAD

**Issue by hannesd** [mathieucarbou/license-maven-plugin#127]
I'd like to adhere to https://google.github.io/styleguide/shell.xml which expects bash files to not have any extension. Currently I am not aware of a configuration option that would allow the license-maven-plugin to correctly deal with this situation.

My suggestion would be to add a boolean option "autoDetect" which, if set to true, will try to find some magic line within the first min(n lines, m bytes) of an extension-less file (unless the whole filename matches an extension or the file is ignored). By "magic line" I mean stuff like "#!/bin/bash".

There would have to be another option like "mapping" (e.g. autoDetectMapping) which allows the user to specify regular expressions that match the magic line, e.g.: &lt;autoDetectMappings>&lt;autoDetectMapping>&lt;search>#!/bin/bash&lt;/search>&lt;style>SCRIPT_STYLE&lt;/style>&lt;/autoDetectMapping>&lt;/autoDetectMappings>

Would there be interest in such a feature? If so, I'd like to give it a try.

**Comment by ljacomet** [comment]
I second this, adding a different twist to it. In Java projects, you end up having `ServiceLoader` files under `META-INF/services/com.service.class.Name` and it would be great to have some support for handling these as well.

**Comment by mathieucarbou** [comment]
in relation to #204
