### ISSUE TITLE
Author Date vs Commit Date confusion

### ISSUE THREAD

**Issue by hazendaz** [mathieucarbou/license-maven-plugin#130]
For those of us using rebasing, we are constantly facing an issue with this plugin getting confused as to what date to use.  So it reverts the year to prior year, then after commit we basically are committing it again.  Can we make this use the commit year instead of author commit date?  That would greatly help out in this situation.

**Comment by mathieucarbou** [comment]
only author names and emails are fetched from the git api. 
i will close this issue, please feel free to re-open it with a test case and ideally a PR if you see a bug.
