### ISSUE TITLE
RFE: update-project-license goal

### ISSUE THREAD

**Issue by jjYBdx4IL** [mathieucarbou/license-maven-plugin#136]
The codehaus maven license plugin has a goal called update-project-license which not only puts the full license text at the root of the module, but also adds it to the build so it ends up in the final jar. Would be great to have an equivalent for the mycila plugin because I prefer the latter one.

**Comment by mathieucarbou** [comment]
this can be done already by controling which file is included in the jar file. This is not up to the MLP to handle packaging.
