### ISSUE TITLE
Add ability to change header style definitions inline in the POM

### ISSUE THREAD

**Issue by beamerblvd** [mathieucarbou/license-maven-plugin#142]
According to the documentation [here](http://code.mycila.com/license-maven-plugin/#changing-header-style-definitions), you can change header style details. For example, for the Java header style, you can change `<firstLine>` from the default `/**` to `/*` (which is necessary for `package-info.java`, to prevent the copyright header from being picked up as the package summary).

The problem is that the _only_ way to do this is to define external XML files containing `<additionalHeaders>` and include those files in `<headerDefinitions>` in the plugin config. This makes it completely impossible to inherit these overridden styles from an organization-wide parent POM that defines rules for all projects in that organization.

You should be able to define/override these header styles inline in the POM itself instead of having to create extra files.

**Comment by beamerblvd** [comment]
Additional, semi-related note: There's an error in the documentation. The example for the XML style override also uses `<javadoc_style>`. Looks like a copy-paste error. I'm assuming that should be `<xml_style>`.

**Comment by mathieucarbou** [comment]
Hi @beamerblvd : could you please either open a PR or put a link to the documentation issue ? I cannot find what you are talking about...

Changing header style definition is so complex that it would require a lot of change in the plugin and several XML tags to parse and validate.
I won't select the issue for 4.0 but help is welcomed for this one!

**Comment by mathieucarbou** [comment]
Implemented in #237 for release 4.2 (ability to define styles inline)
