### ISSUE TITLE
Wrong `license.git.copyrightCreationYear` when the file has more than 10 commits

### ISSUE THREAD

**Issue by brenuart** [mathieucarbou/license-maven-plugin#151]
Although it is not yet released, I gave a try to version `3.1` mainly for its GIT _creation date_ feature.

I noticed the `RevWalk` is configured by default to consider only the last `10` commits. This is causing an issue when computing the creation date of a file that has more than 10 commits in its history. Consequence is the returned date is not the date of the initial commit as expected. Moreover, that date keeps changing as new changes are committed. This case is not catched by the test cases probably because the test repo does not have a file with more than 10 commits in its history.

**Comment by ppalaga** [comment]
Are you sure you do not have just a shallow git clone? I have seen this happening on TravisCI that does a shallow clone by default and the solution was to add `git fetch --unshallow` to travis.yml.

**Comment by brenuart** [comment]
Not as fair as I know. 
Every works fine when I set the property `license.git.copyrightLastYearMaxCommitsLookup` to a large value (like `10000`) to simulate _no limit_.

**Comment by mathieucarbou** [comment]
@brenuart  @ppalaga : I think I will close it: I do not see any way to fix that and there is a workaround, or misconfig here ?
