### ISSUE TITLE
<inlineHeader> is not well documented

### ISSUE THREAD

**Issue by oliverlockwood** [mathieucarbou/license-maven-plugin#182]
It took some digging, including looking into the history of closed issues, to realise that I could achieve what I wanted to using this plugin, with the `<inlineHeader>` configuration tag.

I think this capability could be documented much better.  I'm happy to put together a PR to improve this if that would be of interest.

**Comment by mathieucarbou** [comment]
yes please 👍  Any help is greatly appreciated!

**Comment by mathieucarbou** [comment]
Can you please provide a PR in the README file 👍
