### ISSUE TITLE
Is there any way to see files which causes Some files do not have the expected license header error

### ISSUE THREAD

**Issue by yalamber** [mathieucarbou/license-maven-plugin#190]
Hello, 
I am trying to build one project using this plugin and got below error
`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project ui-ngx: Some files do not have the expected license header`
Is there any way we can see which files is missing license header.

**Comment by flowchartsman** [comment]
does this do what you want?
`mvn license:check |grep "Missing header in:"`

**Comment by mathieucarbou** [comment]
Duplicate of #122
