### ISSUE TITLE
Unable to Configure XML_PER_LINE Without First and End Lines

### ISSUE THREAD

**Issue by emmberk** [mathieucarbou/license-maven-plugin#192]
I'd like an xml header that looks like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- header -->
<...
```
but the default `XML_PER_LINE` style puts a blank line before and after the header line
```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- header -->

<...
```
There doesn't appear to be a way to define a custom `headerDefinition` that doesn't include those extra lines because `firstLine` and `endLine` are required.

**Comment by mathieucarbou** [comment]
Hi @emmberk : the plugin allows to change the definition of a style. You could redefine `XML_PER_LINE` to just remove the `EOL` in the definition. From the quick test I did by removing them in the code, it works
