### ISSUE TITLE
Support for XQuery comments

### ISSUE THREAD

**Issue by phax** [mathieucarbou/license-maven-plugin#239]
Hi,
Eventually you can support for XQuery comments as well.
Specification: https://www.w3.org/TR/xquery-31/#comments
```
Comment         ::= "(:"  (CommentContents  |  Comment)*  ":)"
CommentContents ::= (Char+ - (Char* ('(:' | ':)') Char*)) 	
```
Thanks!

**Comment by mathieucarbou** [comment]
Yes! Please open a PR, this is really easy to do as long as you love regex 😝

**Comment by phax** [comment]
No time yet - it's a nice to have and no must, so priority for me is low (and recursive RegEx are not my favourite ;-) )
