### ISSUE TITLE
HeaderSection is not documented

### ISSUE THREAD

**Issue by electrum** [mathieucarbou/license-maven-plugin#26]
The `HeaderSection` config class is not documented in the generated documentation nor does it appear in the mojo configuration (so my IDE can't autocomplete or validate it).

**Comment by rnc** [comment]
@mathieucarbou  Is it possible to use HeaderSection to override a default pattern e.g. change the build in APACHE-2 from `Copyright (C) ${project.inceptionYear} ${owner} (${email})` to `Copyright  (C) ${project.inceptionYear} ${owner} ` ? Can this be done in the module XML ?

**Comment by mathieucarbou** [comment]
> @mathieucarbou Is it possible to use HeaderSection to override a default pattern e.g. change the pattern in APACHE-2 from `Copyright (C) ${project.inceptionYear} ${owner} (${email})` to `Copyright (C) ${project.inceptionYear} ${owner} ` ? Can this be done in the module XML ?

yes, by redefining the license
