### ISSUE TITLE
Remove / modify custom license not possible

### ISSUE THREAD

**Issue by sonicsdoom** [mathieucarbou/license-maven-plugin#372]
**Version affected**

4.1. and 4.2.rc3

**Describe the bug**

I have added a custom license text header, unfortunately I cannot remove it using the "remove" function.

If I change the license text and call the function "format" again, the old header is not overwritten but extended by the new license text.

If I use a standard license, the functions "remove" and "format" work normally.

**How to Reproduce**

License-file: LICENSE
```
My Licenseinfo

Downloadlink: com.foo.bar
```

My maven-pom:
```
<plugin>
    <groupId>com.mycila</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>4.2.rc3</version>
    <configuration>
        <header>LICENSE</header>
        <includes>
            <include>src/main/**</include>
        </includes>       
    </configuration>
    <dependencies>
        <dependency>
            <groupId>com.foo.bar</groupId>
            <artifactId>my-license</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <phase>compile</phase>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

1st step:
`mvn license:format`

result in java-class:
```
/*
 * My Licenseinfo
 *
 * Downloadlink: com.foo.bar
 */
package com.foo.bar;

import ...
```

2nd step:
`mvn license:remove`

expected behaviour:
License will be removed

actual behaviour:
License is still present in header

console log:

```
[INFO] --- license-maven-plugin:4.2.rc3:remove (default-cli) @ example-core ---
[INFO] Removing license headers...
[INFO] Removing license header from: C:\example\core\src\main\java\com\foo\bar\bar.java
```

**Comment by phax** [comment]
Yes, it is still relevant :)

**Comment by phax** [comment]
@mathieucarbou that feature was previously working and it should hopefully be a simple regression. Do you think you can tackle this one???

**Comment by sonicsdoom** [comment]
Yes it is

Philip Helger ***@***.***> schrieb am Mi., 16. Nov. 2022,
00:53:

**Comment by sonicsdoom** [comment]
Yes

stale[bot] ***@***.***> schrieb am So., 15. Jan. 2023, 13:11:

**Comment by CatPlanet** [comment]
Patiently waiting

**Comment by mathieucarbou** [comment]
@sonicsdoom @phax @CatPlanet : this works as expected. License removal is not linked to the configured license: it is based on header patterns and keywords. There is a keyword parameter you can use so that MLP can detect a header to remove. The default keyword is `copyright`.

**Comment by phax** [comment]
I think the main problem on my side was, that I was using the legacy configuration. After changing to the new configuration layout it seems to work. So my assumption is, that the backporting of the configuration params jn this matter is not 100% clean. But I stopped digging into it.
