### ISSUE TITLE
License enforcement fails on 4.2.rc3

### ISSUE THREAD

**Issue by michael-simons** [mathieucarbou/license-maven-plugin#377]
**Version affected**

4.2.rc3

**Describe the bug**

If I add dependency enforcement to 4.2.rc3 the build fails with

```
 Execution validate of goal com.mycila:license-maven-plugin:4.2.rc3:check failed: Cannot invoke "org.apache.maven.project.MavenProject.getArtifact()" because "project" is null 
```

**How to Reproduce**

Please be so kind and clone https://github.com/michael-simons/neo4j-migrations

* Run `./mvnw license:check`
* Notice it works
* Run `./mvnw -Dlicense-maven-plugin.version=4.2.rc3  license:check`

above exception is thrown.

Here's my config https://github.com/michael-simons/neo4j-migrations/blob/4ee8e0315f51b0a7152afa23665331fa47f79e68/pom.xml#L553-L639

Thank you.

**Comment by michael-simons** [comment]
Nothing has changed. I’d love to have some feedback. Thanks.

**Comment by dbwiddis** [comment]
Looks like a potential regression with this commit:
https://github.com/mathieucarbou/license-maven-plugin/commit/be2dfa259332728615d8a0caa61dcb43de5ae03b

Seems `buildingRequest` isn't in scope and is pulling from the class.  Based on other lines in this file there's some cross-reference between `project` and `buildingRequest` but I'll defer to @hazendaz here to try to explain it.

**Comment by hazendaz** [comment]
will take a look in a few days.

**Comment by michael-simons** [comment]
Please keep it open.

**Comment by hazendaz** [comment]
haven't forgotten about this, just haven't had time.  The code was changed because maven changed the method signature.  Will need to dig more into this specific issue but did want to at least comment on why it changed on #be2dfa2

**Comment by michael-simons** [comment]
Keep it open please.

**Comment by michael-simons** [comment]
Thanks for re-opening this. 

Can I maybe help solving this?

**Comment by dbwiddis** [comment]
The problem is in [this commit](https://github.com/mathieucarbou/license-maven-plugin/issues/377#issuecomment-1202019857). If you can read @hazendaz mind to figure out what he meant, please do!

**Comment by michael-simons** [comment]
I forked the project and the first thing I noted, that the `*IT*  tests do not run at all… :( So `MavenProjectLicensesIT` does not do anything.

**Comment by hazendaz** [comment]
The original change I did was only to use newer dependency tree as its method signature changed.

```from maven
    DependencyNode buildDependencyGraph( ProjectBuildingRequest buildingRequest, ArtifactFilter filter )
        throws DependencyGraphBuilderException;
```

@michael-simons Thanks for PR to try to remediate the issue.  I've approved it to run and reviewing it now...
