### ISSUE TITLE
Add removeTrailingSpaces option

### ISSUE THREAD

**Issue by mathieucarbou** [mathieucarbou/license-maven-plugin#4]
https://code.google.com/p/maven-license-plugin/issues/detail?id=93
### Reported by sewe@st.informatik.tu-darmstadt.de, Feb 3, 2011

Blank lines in the header files are never indented. Thus, one always gets the following (spaces denoted by '.'):

```
/**
.*.You.may.obtain.a.copy.of.the.License.at
.*
.*...http://www.apache.org/licenses/LICENSE-2.0
.*/
```

Its impossible to obtain the following (note the extra '.' on the otherwise blank line):

```
/**
.*.You.may.obtain.a.copy.of.the.License.at
.*.
.*...http://www.apache.org/licenses/LICENSE-2.0
.*/
```

This is the case even if the line is just blank, but not empty, i.e., if it does contain some whitespace; the whitespace is always stripped.

Probably an option like <indentBlankLines> would be useful, in addition to preserving all whitespace found in the header file.
### Feb 3, 2011 Delete comment Project Member 1 mathieu.carbou

Hi,
This is something that has been added after an issue request because a lot of IDEs are removing unused spaces at the end of the lines. Thus the second header may be transformed by your IDE in the first header. That's why unused spaces are removed.
### Feb 3, 2011 Delete comment 3 sewe@st.informatik.tu-darmstadt.de

For the record and the benefit of others:  issue 32  requested removal of trailing whitespaces. That being said, it would be great if this were configurable (with <removeTrailingSpaces>true</removeTrailingSpaces> being the default).
### Feb 3, 2011 Delete comment Project Member 4 mathieu.carbou

 Yes good idea. An option would be the best. I fear I won't have any time this week to check all issues.  If you have a patch ready it would accelerate it.
Mat'

**Comment by mirabilos** [comment]
I chose this plugin over another exactly *because* it *does* strip trailing whitespace ☺

We have a code rule that no trailing whitespace is allowed.

**Comment by mathieucarbou** [comment]
Yes. I think this report was about to add the option `removeTrailingSpaces` defaulted to true, and some people would like to set it off to keep the white spaces.
