### ISSUE TITLE
License headers shouldn't be in Javadoc style

### ISSUE THREAD

**Issue by william-tran** [mathieucarbou/license-maven-plugin#43]
In most open source java libraries the header looks like:

```
/*
 * The header
 */
```

This plugin uses a javadoc style:

```
/**
 * The header
 */
```

 This becomes a problem when generating javadocs, because the license header content gets into all your documentation.

**Comment by lucianoprea** [comment]
> You are able to redefine the comment styles used. See the documentation for it. If it does not work, please reopen with more details to be helped.

it will be nice to paste a link to that section in documentation :) thanks
