### ISSUE TITLE
Avoid SonarLint glitch

### ISSUE THREAD

**Issue by onacit** [mathieucarbou/license-maven-plugin#431]
**Describe the feature**

Change the license text so that the SonarLint won't complain about the commented out code blocks.

**Any alternative you've considered ?**

```
Licensed under the Apache License, Version 2.0 (the "License"); // SonarLint believes this line is a commented-out code
you may not use this file except in compliance with the License.
```

```
Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
```

https://stackoverflow.com/q/45874511/330457

**Comment by hazendaz** [comment]
@onacit Not clear on the ask here, are you wanting us to fix our configuration so our files no longer include semi-colon or something with how plugin works when applying to other repos?  I'm fixing our pom for our project but would like clarification.

**Comment by onacit** [comment]
@hazendaz Thank you for your comment.

There are, as you requested, two prospectives here.

* Remove (or replace with other character) the tailing semi-colon(`;`) so that the SonarLint stops complaining.
* Tell SonarLint that the line ends with the semi-colon, actually, is not a comment code.

I think I was asking to remove (or replace) the semi-colon. Yet, now, I'm worried that semi-colon(`;`) is part of the license itself.

Thank you.

**Comment by onacit** [comment]
Oh I see the whole text including the line ends with the semi-colon(`;`) came from the original section.

[https://www.apache.org/licenses/LICENSE-2.0](https://www.apache.org/licenses/LICENSE-2.0).

Sorry for making you bother. I think it's beyond what LMP can't help.
