### ISSUE TITLE
Replace dependabot with renovate

### ISSUE THREAD

**Issue by hazendaz** [mathieucarbou/license-maven-plugin#496]
Currently this project uses dependabot.  Dependabot has a huge negative impact on contributors that had repos forked long before that which results in excessive downstream pull requests.  It also isn't as good at detection.  A simple and extremely more effective solution is to use Renovate which is also free.

Steps to introduce.

- Go to https://github.com/marketplace/renovate
- Add it for this project
- Merge the renovate.json PR it raises
- Pin the issue tracking created afterwards for better tracking of what this project uses
- Remove the .github/dependabot.xml file
- Any existing ignores if any are as simple as closing raised new PRs which will update the issue tracking

Example links to see this in action (over at mybatis)
- https://github.com/mybatis/mybatis-3/issues/2641
- https://github.com/mybatis/mybatis-3/pull/2764

Effort to switch, minutes...

**Comment by hazendaz** [comment]
to see downstream issues dependabot causes for example https://github.com/hazendaz/license-maven-plugin/pull/107.  In past week, if you look at PRs over there on the fork, I've had to close out many from dependabot which is a pain and long, long standing defect with github's dependabot since before they owned it.

**Comment by ctubbsii** [comment]
For what it's worth, GitHub does allow you to disable dependabot checks on forks... and it's off by default now. So, I don't think this is strictly necessary. See my comment on https://github.com/revelc/formatter-maven-plugin/pull/711#pullrequestreview-1336156222

**Comment by hazendaz** [comment]
If the fork is new that is true.  If it is not, that is untrue.  It's still open defect.  Github said only way to fix is to delete fork and start over.  I get updates every few weeks on it.

Dependabot is weak anyways.  I know you have not used renovate.  I have for years.  It's now the defacto solution and has big backing.  At my job we ran a 2k repo pilot for 3 years that I led.  It's now going global to 25k repos.  If you have never seen it work. Look at my fork of formatter.  This isn't the place to go into more details but you won't be too happy once you see what I'm doing.


Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
See https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-1326137957

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ctubbsii** [comment]
The link you provided says you can delete/recreate the fork **OR** `click Disable`. It's a one-button click. Whether or not the maintainer chooses to go with renovate, I just wanted to make sure that they know it's not strictly necessary to avoid the spam. It's a just a one button click for any existing repos. That button has been there for a long time. The only change is whether it's on by default when you fork.

**Comment by hazendaz** [comment]
It's not on my fork hence the ongoing issue.  No button to disable even.  It's the same on dozens on them.  Maybe we can zoom sometime and you can show me what I'm missing.  I did kill it on my fork there for formatter and I'm using renovate there now.  I simply deleted the yaml file so it's done now.  May be worth showing to why renovate is better.  PRs even are better.  Interaction easier, etc.  No typing just ticking boxes. And they have more user growth, big backing. Etc.  Even partnered with aws. Sure dependabot is owned by GitHub...err microsoft...but that wasn't always the case and I'm sure my issues are for that reason.  I got it added in most places I touched and from the prior service not v2 yaml.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ctubbsii** [comment]
> It's not on my fork hence the ongoing issue. No button to disable even.

Weird. For your fork, it should be at: https://github.com/hazendaz/license-maven-plugin/settings/security_analysis
The button should be red if enabled. All mine are off.

**Comment by hazendaz** [comment]
Will check again tomorrow.  When I checked last it was off.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mathieucarbou** [comment]
I've looked at Renovate and even if I see its value for some other project, for this one, I don't see any advantage over dependabot, besides requiring a more complex config and being less Github-integrated.

I would highly prefer you disable dependabot on your forks (I don't even know how you had that enabled: I have many forks myself and never got any Prs or alerts regarding dependabot on any of my forks...)

Let's keep this issue in the backlog for now.

**Comment by hazendaz** [comment]
That's fine but there is zero configuration that needs set.  Today you have a dependabot file.  Renovate also adds a file only to indicate you agree to use it.  In fact the first pull request purpose after signing the repo up is so one understands how it works.  You never again need touch that file.  After that it opens an issue that is for everyone to easily see all dependencies used.  I'll get you a few links to show its usage.  From that point anyways you never have to type like one does with dependabot and it further tacks what is blocked.  So you as owner can just interact on one spot without typing your intentions at all times.  And yes one could configure it like crazy but there is basically no need to ever do so.

Anyway we have 2k strong on it for 3 years and our firm is now rolling it out to 25k repos.  It's better to see it live anyways but totally your call in end.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mathieucarbou** [comment]
I personnel don't mind  changing but I just still does not see the value for this project, even if I completely agree with all what you said :-) 
I am not in a company use case... For MLP, one or the other is enough for the needs. Dependency management for MLP is far from being critical and dependabot is more than enough and easier since well integrated inside GitHub's interface.

**Comment by hazendaz** [comment]
OK to just reset.

See https://github.com/mathieucarbou/license-maven-plugin/blob/fd7362c9b011d66b29f26a79464372c91b73d466/license-maven-plugin/src/test/resources/check/pom.xml

Dependabot fails to just update all poms.  Not to mention it raised a CVE fix we likely just overlooked.  Renovate will address these.

In case where everyone is not really cool with external non github solution (dependabot wasn't either at one time), I can just setup my local and let it do the work and merge in.  Since this specific project just forces squash, you won't really see that in history unless 1 to 1 merge.

That said, that is the approach I'll take with this and others I'm mostly concerned with.  While notes on how to shut up dependabot, none actually work if one came before it was consumed by github (ie greatly affects me but clearly not others).  That may have to do with being part of that track originally and separately setup entirely with dependabot in general.  As noted, its still reported to github regularly and I keep getting alerts as well when people go after github for poor behavior there.  Regardless, keep things as is, going to close this PR, I'll setup what I need, I'll adjust my default branch which also resolves the dependabot madness for me, and I'll raise renovate PRs that way which if you look I merge most of these anyways.  That way, no new stuff there, I'm happy, everyone is happy, and we can proceed as usual.

Probably no need to discuss more but a thumbs up or down to my approach will work.  I won't bother bringing up the concern again post this as the model I've proposed here is satisfactory to me, think its clearly ok to the group, and we continue on working on real issues, the code :)

**Comment by hazendaz** [comment]
Reopening this as I would like to have this reconsidered once again.  Just like my prior note, dependabot is not finding everything.  I had to again manually fix some usage.  I also have zero clue what dependabot thinks we want, don't want, or what even even use.  If setup is a concern, grant me enough access here and within 10 minutes it will be live.  It is integrated to github btw.  Many in the market place are entirely separate platforms with very little integration this one is not.  If team doesn't like it after using it then fine remove it but give it a chance first.

On current dependabot we didn't even setup GHA portion as it has to be told everything, so we miss all those updates.

On renovate dashboard that dependabot does not have, see an example -> https://github.com/hazendaz/base-parent/issues/437

Please reconsider this given in 99% of the cases, I'm the only one merging these as it is.  And for my sanity, I prefer to have the defect in dependabot resolved.  It still sends PRs constantly to forks.  I'd like to be more involved here and this one is super important to me because of the level it actually works.  I'm already 100% provisioned with them for long time so setting any repo to it takes roughly 2 minutes.  Long enough for it to send me 2FA to approve it and select the repo.  In fact, I have the dashboard up now and if I am part of this org, done deal quickly.  If anything else, it will at least tell us what our code is made up of.

One thing of note, you still 100% retain integrated dependabot for security vulnerabilities.  That part doesn't do away.  This is just for the day to day stuff.
