### ISSUE TITLE
Support ignore the year check

### ISSUE THREAD

**Issue by Leo6Leo** [mathieucarbou/license-maven-plugin#611]
**Describe the feature**
If we don't pass in the <year> variable, then don't check the year.
```
<plugin>
        <groupId>com.mycila</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>${mycila.license.plugin.version}</version>
        <configuration>
          <licenseSets>
            <licenseSet>
              <header>com/mycila/maven/plugin/license/templates/APACHE-2.txt</header>
              <includes>
                <include>src/**/*.java</include>
              </includes>
              <excludes>
                <exclude>**/DataPlaneContract.java</exclude>
              </excludes>
            </licenseSet>
          </licenseSets>
          <properties>
            <owner>Authors</owner>
            <email>test@googlegroups.com</email>
            <year>2018</year>
          </properties>
        </configuration>
        <executions>
          <execution>
            <id>check-license</id>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>verify</phase>
          </execution>
        </executions>
      </plugin>
```

**Any alternative you've considered ?**

_A clear and concise description of any alternative solutions or features you've considered._

Same for other variables, like if we don't pass email, then won't check email.

**Comment by hazendaz** [comment]
keep open

**Comment by Leo6Leo** [comment]
keep open

**Comment by dbwiddis** [comment]
I wrote some initial code in #323 attempting to address my request #309.  It may be useful for anyone wanting to implement this.

**Comment by hazendaz** [comment]
Thanks @dbwiddis , I reopened that one.  I really dislike the stale bot, most of us don't have time to address everything so fast and things get lost otherwise.

**Comment by dbwiddis** [comment]
There could be a lot of issues like this implemented with better "tokenization" of the header.

And we could definitely increase the timeout time on the stale bot to much longer.  The fact that the majority of emails I get from this repo are from stale bot indicate that very little new code is being written, people want features but don't want to contribut the code for them, and the maintainers are overtasked elsewhere. :(

**Comment by mathieucarbou** [comment]
@Leo6Leo : 

- if the year is not important to you, please choose another template with a year that is fixed in the template. `com/mycila/maven/plugin/license/templates/APACHE-2.txt` required a year to be fed

- if you need to handle years properly, use the git plugin to source the year range from the files

- If you want to create your own rules about what to check or not based on properties, use Mavan mechanism like profiles, or MLP license sets
