### ISSUE TITLE
Adding Gradle related file extensions

### ISSUE THREAD

**Issue by uyw4687** [mathieucarbou/license-maven-plugin#631]
**Describe the feature**

Adding Gradle related file extensions(.gradle, .gradle.kts)

**Any alternative you've considered ?**

Adding it in [gradle side plugin settings](https://github.com/line/license-gradle-plugin-git/blob/42871e4ff04b3806596ff14d80f7b45086d71f3a/src/main/groovy/nl/javadude/gradle/plugins/license/License.groovy#L202C2-L210)

but in this way, it is harder to keep the consistency between the two

cc @minwoox

**Comment by uyw4687** [comment]
How do you say, @mathieucarbou ?

**Comment by mathieucarbou** [comment]
Yes, sure. Please send a PR :-)
