### ISSUE TITLE
Support executions on only changed files(for PR checks)

### ISSUE THREAD

**Issue by uyw4687** [mathieucarbou/license-maven-plugin#634]
**Describe the feature**

It would be better to use this in CI(PR check) if this plugin supports executions on only changed files like in [sonar analysis](https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/pull-request-analysis/).
Currently my project takes 20mins to execute for the whole file.
cc @minwoox

**Any alternative you've considered ?**

None yet.

**Comment by hazendaz** [comment]
Agree this would be great to have, the plugin is slow especially if using git to determine timestamps.

**Comment by mathieucarbou** [comment]
Such mechanism would require maintaining a sort of cache, and then comes the complexity to know when to invalidate this cache. There is no trivial rules here, and computing a hash would be as slow as checking licenses.

@uyw4687 : the plugin already has some concurrency mechanism in place that you can control with `license.concurrencyFactor` and `license.nThreads`. If doing a lot of I/O with git, maybe you can try increasing the numbers especially if the number of cores of your system is low (i.e. in containers or VM)

**Comment by uyw4687** [comment]
Thanks @mathieucarbou I was actually talking about Git diff. Sorry for not elaborating on this.
So we can make a feature that performs the license validity check only with changed files which we can know by git diff.
This way, we can limit the responsibility of the failure to the extent of the files changed by a pull request.

**Comment by mathieucarbou** [comment]
> Thanks @mathieucarbou I was actually talking about Git diff. Sorry for not elaborating on this.
> So we can make a feature that performs the license validity check only with changed files which we can know by git diff.
> This way, we can limit the responsibility of the failure to the extent of the files changed by a pull request.

Yes! It is definitely a good idea to use the git extension to filter the files to scan.
