### ISSUE TITLE
DefaultInlineHeaderStyles is not working

### ISSUE THREAD

**Issue by pipelineRat** [mathieucarbou/license-maven-plugin#652]
**Version affected**

Version 4.2
Version 4.3

**Describe the bug**

I have followed the example detailed on documentation for the "SMILEY_STYLE" inline style: https://mycila.carbou.me/license-maven-plugin/

This does not work, I have tested this with 4.2 and 4.3, and no header is added to my "test.txt" file. When I remove the "SMILEY_STYLE" mapping, the a header is added.

**How to Reproduce**

```
<plugin>
    <groupId>com.mycila</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <configuration>
      <licenseSets>
        <licenseSet>
          <header>src/main/license/license.txt</header>
        </licenseSet>
      </licenseSets>
      <mapping>
        <txt>SMILEY_STYLE</txt>
      </mapping>
      <defaultInlineHeaderStyles>
        <defaultInlineHeaderStyle>
          <name>SMILEY_STYLE</name>
          <firstLine>:(</firstLine>
          <beforeEachLine> ( </beforeEachLine>
          <endLine>:(</endLine>
          <firstLineDetectionPattern>\:\(</firstLineDetectionPattern>
          <lastLineDetectionPattern>\:\(</lastLineDetectionPattern>
          <allowBlankLines>false</allowBlankLines>
          <multiLine>false</multiLine>
        </defaultInlineHeaderStyles>
      </defaultInlineHeaderStyles>
    </configuration>
</plugin>
```

**Comment by pipelineRat** [comment]
The issue is with the name field. The job fails if the you use a capitalized name such as "SMILEY_STYLE" in the name field when defining the inline style.

However if you use lowercase, such as "smiley_style" the inline style does work as intended.

I will mark as closed, since I found a workaround

**Comment by stacktracer** [comment]
Here's the line responsible: https://github.com/mathieucarbou/license-maven-plugin/blob/license-maven-plugin-4.3/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentFactory.java#L55

Seems like maybe just a copy-paste bug. I can't think of a reason `toLowerCase()` needs to be called on `entry.getValue()`.
