### ISSUE TITLE
plugin build setting

### ISSUE THREAD

**Issue by dylan-tao** [mathieucarbou/license-maven-plugin#673]
**Describe the feature**

maven build target file： license-plugin-report.xml， support xml cust targetDirectory and targetFilename.
```
<configuration>
  <targetDirectory>${project.reporting.outputDirectory}/cache</targetDirectory>
  <targetFilename>license-plugin-report.xml</targetFilename>
</configuration>

```
**Any alternative you've considered ?**
other nothing, thanks!

**Comment by dylan-tao** [comment]
> **Describe the feature**
> 
> maven build target file： license-plugin-report.xml， support xml cust targetDirectory and targetFilename.
> 
> ```
> <configuration>
>   <targetDirectory>${project.reporting.outputDirectory}/cache</targetDirectory>
>   <targetFilename>license-plugin-report.xml</targetFilename>
> </configuration>
> ```
> 
> **Any alternative you've considered ?** other nothing, thanks!

How is the progress now？

**Comment by hazendaz** [comment]
HI @dylan-tao , same comment as I had on other repo you raised similar ask.  What is the purpose of doing so?  Example doesn't make sense here, maybe not add 'cache' to a directory like that as I don't think that is what you meant.  However, still don't understand the ask.  If we can make sense of the why here, it would likely be best if you could contribute a pull request but before doing so please explain what you are trying to achieve.  Thanks.

**Comment by dylan-tao** [comment]
> HI @dylan-tao , same comment as I had on other repo you raised similar ask. What is the purpose of doing so? Example doesn't make sense here, maybe not add 'cache' to a directory like that as I don't think that is what you meant. However, still don't understand the ask. If we can make sense of the why here, it would likely be best if you could contribute a pull request but before doing so please explain what you are trying to achieve. Thanks.

Hi, Brother. I am now doing unified governance of Maven plug-in reports, and expect to have multiple reports generated by Maven plug-ins in the same directory, as other plug-ins such as PMD can currently do. So expect license-maven-plugin and spotbugs-maven-plugin to already set the directory where the report will be generated. Look at the picture below

**Comment by dylan-tao** [comment]
![image](https://github.com/mathieucarbou/license-maven-plugin/assets/13051685/5ce54db6-e88b-4a90-9a56-38786b3c23d6)

**Comment by dylan-tao** [comment]
![image](https://github.com/mathieucarbou/license-maven-plugin/assets/13051685/705b9cfb-edd1-4321-aef3-d09d10e1f526)

**Comment by dylan-tao** [comment]
> HI @dylan-tao , same comment as I had on other repo you raised similar ask. What is the purpose of doing so? Example doesn't make sense here, maybe not add 'cache' to a directory like that as I don't think that is what you meant. However, still don't understand the ask. If we can make sense of the why here, it would likely be best if you could contribute a pull request but before doing so please explain what you are trying to achieve. Thanks.

![image](https://github.com/mathieucarbou/license-maven-plugin/assets/13051685/0bd88f5e-c0f9-45f6-86df-c74dab8bc550)

**Comment by dylan-tao** [comment]
> @dylan-tao Do you have time to offer a pull request for this support?

I am very sorry, when I read the source code found that it has been supported, but the official document does not say, thank you again.

example:
```
         <reportFormat>xml</reportFormat>
          <reportLocation>${project.report.cache.directory}/license-plugin-report.xml</reportLocation>
```
code source:
```
  /**
   * The location where to write the report of the plugin execution (file processed, action taken, etc).
   * <p>
   * "PRESENT" means the file has a header (check goal)
   * <p>
   * "MISSING" means the header is missing (check goal)
   * <p>
   * "NOOP" means no action were performed (remove or format goal)
   * <p>
   * "ADDED" means a header was added (format goal)
   * <p>
   * "REPLACED" means a header was replaced (format goal)
   * <p>
   * "REMOVED" means a header was removed (format goal)
   * <p>
   * "UNKNOWN" means that the file extension is unknown
   * <p>
   * Activated by default.
   */
  @Parameter(property = "license.report.location", defaultValue = "${project.reporting.outputDirectory}/license-plugin-report.xml")
  public File reportLocation;

  /**
   * Format of the report.
   * <p>
   * Can be (case-insensitive): 'xml', 'json'.
   * <p>
   * Default is XML.
   */
  @Parameter(property = "license.report.format")
  public String reportFormat;
```
