### ISSUE TITLE
Propose removing 'System.getenv()'

### ISSUE THREAD

**Issue by hazendaz** [mathieucarbou/license-maven-plugin#708]
The default properties are gathered System.getenv() grabbing the entire environment set of properties which is highly unpredictable per machine and known to be possible to manipulate by outside processes.  Spotbugs just added checks for this on give or take decade old information stating its subject to attacks.  Yes sub processes will get same value as picked up by maven to start with but point is any other running processes in between could be changing them without user realizing it.

Further per javadoc, it states 'When passing information to a Java subprocess, [system properties](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#EnvironmentVSSystemProperties)are generally preferred over environment variables.'

A CI platform for example is not likely to match a developers machine.  For example, github is not going to enforce such flags this plugin needs as ENV variables, one could script them but why, and running this doesn't even require that level of support.  It is already supporting far too much.

It uses everything else as expected from the project (grabbed from maven) then gets system properties (-D) like most plugins do.  In fact, with modern maven you can use maven.config since maven 3.3.9 can be used to store -D options permanently if wanted, the pom obviously can be used to create system variables as well, and can even have default run so something like 'mvn' would magically run with lots of extra -D options.  And I suspect most other plugged in data is coming from the resolutions in the header templates.

Therefore I propose we remove 'System.getenv()' from usage as well as from documentation.

It should be important to note the order of events here also makes them less useful.  

-> System.getenv()
-> project from maven items
-> Exposed defaultProperty list in pom
-> Then -D options
-> Override more with license set properties (unless sent with -D option)
-> Override further with data collected from providers (git, svn, fs)

With each subsequent item it overrides the prior one.  So rather than us loading what is sometimes a very large system env that is likely to be entirely overwritten by most users, subject to changing between builds without direct warning, I believe it should go away. 

I'd go as far as to get rid of defaultPropertyList too because its IMO a lot of duplication for already existing methods, but that would need deprecated to indicate users cleanup their poms.  This one is hard to deprecate outside just deleting it.  So the release notes could just state its no longer supported.

**Comment by mathieucarbou** [comment]
Sadly some systems like docker are using env as an first citizen class to pass / customise what's running inside. 
also, some CI systems are using envs for globally applied props everywhere.

This is not an option to drop that : too many possible breakings.

**Comment by mathieucarbou** [comment]
I am closing because this is not something that can be implemented in a backward compatible way. All envs are allowed in templates.
