### ISSUE TITLE
Propose we deprecate 'defaultPropertyList' with maven way to manage

### ISSUE THREAD

**Issue by hazendaz** [mathieucarbou/license-maven-plugin#710]
Presumably this exists solely for properties someone wants to add that don't exist and we don't know about for some custom adjustments in files.  I haven't looked far enough to know why exactly yet we would support this exposure.  However, maven since maven 3.3.9 has maven.config that can store as many properties as they want.   Given how global half the properties are being treated that would be effectively a -D option type without the typing.  And maven is currently feverishly discussing dropping support for anything before 3.6.3 meaning we would have to follow suite and many mojo's already did.

This one I find less of an issue in design as to the other tickets I opened but feel property handling here for what resolves is pretty over the top.  Plus maven provides us all this out of the box by calling session already as noted so its pretty easy for us to drop extra support and not actually lose anything.

**Comment by mathieucarbou** [comment]
Sorry, I am a bit lost ;-) 
Which part of the code exactly ?
