### ISSUE TITLE
Propose we drop 'starEncrypt' method

### ISSUE THREAD

**Issue by hazendaz** [mathieucarbou/license-maven-plugin#711]
This method

```
  static String starEncrypt(String str) {
    if (str == null) {
      return null;
    }
    return str.replaceAll(".", "*");
  }
```

Exists simply to print the fact a password exists and it takes that password and changes it out for exact number of asterisks as the password.  I find this useless behavior that does give away the users password size so slightly insecure.  We should not even try to print a password to start with as its too much of a security risk and not worth the value.  I think if password exists and we really need to acknowledge it exists, simply note some set asterisks without actually looking at the value.  I've already done this on a branch and it removed excessive testing around making sure the pwd size matches.

Note when its missing, it already states its just missing FWIW.  So from user perspective they know the problem.  Additionally sonar is flagging this code as the use of regex is suspect for what is being done.

Other options, if 100% needed,

```
  static String starEncrypt(String str) {
    if (str == null) {
      return null;
    }
    return RandomStringUtils.random(str.length(), "*");
  }
```

Does the same thing in same way.  Its random in that it would use random values but the single * will just be repeated.  Guava has a better option but not in our source deps (is in test), and if we bump to java 11 where most other plugins have started going we would get it directly from java (source from guava).

But my main opinion is if we must we acknowledge a pwd was found but we do not expose the size of it and cleanup the logic so its not overly complicated.

**Comment by mathieucarbou** [comment]
I agree, this thing was added when svn support was added. No need to print stats in the log line.= for the connection.
