### ISSUE TITLE
"Detailed Maven documentation" not present

### ISSUE THREAD

**Issue by mykelalvis** [mathieucarbou/license-maven-plugin#761]
**Version affected**

4.4

**Describe the bug**

No site generated documentation regarding goals, etc appears to be present.  I assume the site docs are what is meant by "[Detailed Maven documentation](https://oss.carbou.me/license-maven-plugin/#detailed-maven-documentation)" but cannot be sure.  

As an aside, changes from 4.3 (previous version) _seem_ like non-semver breaking configuration changes, but I could be wrong about that because I don't know what those configs are, at present.

**How to Reproduce**

1. Go to https://oss.carbou.me/license-maven-plugin
2. Search for "Detailed Maven documentat"
3. Click link
4. Go nowhere from there

**Comment by mathieucarbou** [comment]
Hello,

Do you mean that ?

![Screenshot_20240510-223411](https://github.com/mathieucarbou/license-maven-plugin/assets/61346/7141e7a4-9678-4061-9c88-2f8331572d93)

Please do not hesitate to propose a change through a PR to improve if you feel it should be improved.

Thanks.

**Comment by hazendaz** [comment]
@mathieucarbou I think if you drill deep enough the maven site pages portion are not showing up and getting 404s.  At least that is what I saw but not sure if that was working before or not as not looked at in some time.

**Comment by mathieucarbou** [comment]
Oh that's right ! I have 404 errors too. Weird because I generated the site and uploaded it.

I will anyway remove the ref to 4.4 and replace it by 4.5 this weekend after the new release.

Thanks for pointing that out!

**Comment by mathieucarbou** [comment]
fixed!
