### ISSUE TITLE
Ready to release 4.6 

### ISSUE THREAD

**Issue by hazendaz** [mathieucarbou/license-maven-plugin#832]
Lets go ahead and get 4.6 released.

Here is what is in it

- Add apache-2 no email support
- Use JSR330 inject rather than deprecated component
- Use try with resources
- Small api changes on java end (ie closeable exchanged to autocloseable)
- Require maven 3.6.3 per maven guildelines
- More lambdas
- Test cleanup
- Some logging level checks so it doesn't run expensive checks and then not log
- Better handling of filepath that was repeating path replacements
- Lots of library / plugin updates

I don't expect any real improvement on speed nor did my tests show any.  However, I think this is where we want to alert this will be last java 8 release per my ticket #831.  Then we can start moving onto 11 and doing any new cleanup we can get from that and follow up in few weeks after with a java 11 release noting that is likely last there too, followed by doing a proper java 17.  FWIW overriding jgit still works with this using the 7.0 release of jgit but better to error on side of caution and jgit is not really likely to keep releasing old versions when so many frameworks have moved.

**Comment by mathieucarbou** [comment]
Release done. Thanks a lot!
