### ISSUE TITLE
Unable to license check generated source files if useDefaultExcludes is true

### ISSUE THREAD

**Issue by eitzenbe** [mathieucarbou/license-maven-plugin#840]
**Version affected**

4.6

**Describe the bug**

i have generated source files in target/generated-sources/.../.java

Now when including 
<includes>
   <include>**/target/**</include>
   <include>**/target/generated-source/**/*</include>
</includes>

I would have expected that the target folder is included OVERWRITING the default exclude

**How to Reproduce**

Place a java (or any other) file into target/generated-sources/.../X.java and configure the plugin using the settings above

Happy to supply a fix for that as at least according to the code the **/target/** should have been removed from the excludes and thus the second include should trigger

**Comment by eitzenbe** [comment]
stupid me ;) the includes must be inside of the <licenseSet>

**Comment by hazendaz** [comment]
no worries, glad you figured it out.  This may help others in the future :)
